"""
Report export — PDF and Excel generation for downloadable reports.
"""

import io
from decimal import Decimal
from datetime import date
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

from app.modules.reports.schemas import (
    AccommodationReport,
    RestaurantReport,
    InventoryReport,
    TaxRemittanceReport,
)


# ── PDF Export ────────────────────────────────────────────────

def generate_accommodation_pdf(
    report: AccommodationReport,
    hotel_name: str,
) -> bytes:
    """Generate a PDF accommodation report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=6*mm)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=11, textColor=colors.grey)

    elements = []

    # Header
    elements.append(Paragraph(f"{hotel_name}", title_style))
    elements.append(Paragraph("Accommodation Report", styles["Heading2"]))
    elements.append(Paragraph(
        f"Period: {report.period_start.strftime('%B %d, %Y')} — {report.period_end.strftime('%B %d, %Y')}",
        subtitle_style
    ))
    elements.append(Spacer(1, 10*mm))

    # KPIs table
    kpi_data = [
        ["Metric", "Value"],
        ["Total Revenue", f"₦{report.total_revenue:,.2f}"],
        ["Occupancy Rate", f"{report.occupancy_rate}%"],
        ["ADR", f"₦{report.adr:,.2f}"],
        ["RevPAR", f"₦{report.revpar:,.2f}"],
        ["Rooms Sold", str(report.rooms_sold)],
        ["Room-Nights Available", str(report.total_room_nights)],
    ]
    kpi_table = Table(kpi_data, colWidths=[150, 150])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 8*mm))

    # Revenue by room type
    if report.revenue_by_room_type:
        elements.append(Paragraph("Revenue by Room Type", styles["Heading3"]))
        rt_data = [["Room Type", "Revenue", "Nights Sold", "Avg Rate"]]
        for rt in report.revenue_by_room_type:
            rt_data.append([
                rt.room_type,
                f"₦{rt.total_revenue:,.2f}",
                str(rt.nights_sold),
                f"₦{rt.average_rate:,.2f}",
            ])
        rt_table = Table(rt_data, colWidths=[120, 120, 100, 120])
        rt_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(rt_table)

    elements.append(Spacer(1, 15*mm))
    elements.append(Paragraph(
        f"Generated by Hosila PMS • {date.today().strftime('%B %d, %Y')}",
        subtitle_style,
    ))

    doc.build(elements)
    return buffer.getvalue()


def generate_tax_remittance_pdf(
    report: TaxRemittanceReport,
    hotel_name: str,
) -> bytes:
    """Generate a PDF tax remittance report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=6*mm)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=11, textColor=colors.grey)

    elements = []

    # Header
    elements.append(Paragraph(f"{hotel_name}", title_style))
    elements.append(Paragraph("Tax Remittance Report", styles["Heading2"]))
    elements.append(Paragraph(
        f"Period: {report.period_start.strftime('%B %d, %Y')} — {report.period_end.strftime('%B %d, %Y')}",
        subtitle_style
    ))
    elements.append(Spacer(1, 10*mm))

    # Summary table
    summary_data = [
        ["Tax Type", "Total Collected", "Already Remitted", "Pending"],
        [
            "Federal VAT",
            f"₦{report.federal_vat.total_amount:,.2f}",
            f"₦{report.federal_vat.remitted_amount:,.2f}",
            f"₦{report.federal_vat.pending_amount:,.2f}",
        ],
        [
            "State TDL",
            f"₦{report.state_tdl.total_amount:,.2f}",
            f"₦{report.state_tdl.remitted_amount:,.2f}",
            f"₦{report.state_tdl.pending_amount:,.2f}",
        ],
        [
            "Service Charge",
            f"₦{report.service_charge.total_amount:,.2f}",
            f"₦{report.service_charge.remitted_amount:,.2f}",
            f"₦{report.service_charge.pending_amount:,.2f}",
        ],
    ]

    table = Table(summary_data, colWidths=[100, 130, 130, 130])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 8*mm))

    # Department breakdown
    if report.by_department:
        elements.append(Paragraph("Breakdown by Department", styles["Heading3"]))
        dept_data = [["Department", "VAT", "TDL", "Service Charge"]]
        for dept in report.by_department:
            dept_data.append([
                dept.department.replace("_", " ").title(),
                f"₦{dept.vat:,.2f}",
                f"₦{dept.tdl:,.2f}",
                f"₦{dept.service_charge:,.2f}",
            ])

        dept_table = Table(dept_data, colWidths=[120, 120, 120, 120])
        dept_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(dept_table)

    elements.append(Spacer(1, 15*mm))
    elements.append(Paragraph(
        f"Generated by Hosila PMS • {date.today().strftime('%B %d, %Y')}",
        subtitle_style,
    ))

    doc.build(elements)
    return buffer.getvalue()


# ── Excel Export ──────────────────────────────────────────────

_header_font = Font(bold=True, color="FFFFFF", size=11)
_header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
_thin_border = Border(
    left=Side(style="thin"), right=Side(style="thin"),
    top=Side(style="thin"), bottom=Side(style="thin"),
)


def _style_header_row(ws, row_num: int, col_count: int):
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.font = _header_font
        cell.fill = _header_fill
        cell.alignment = Alignment(horizontal="center")
        cell.border = _thin_border


def generate_accommodation_excel(report: AccommodationReport, hotel_name: str) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Accommodation Report"

    ws.append([f"{hotel_name} — Accommodation Report"])
    ws.append([f"Period: {report.period_start} to {report.period_end}"])
    ws.append([])

    # KPIs
    ws.append(["Metric", "Value"])
    _style_header_row(ws, 4, 2)
    ws.append(["Total Revenue", float(report.total_revenue)])
    ws.append(["Occupancy Rate", f"{report.occupancy_rate}%"])
    ws.append(["ADR", float(report.adr)])
    ws.append(["RevPAR", float(report.revpar)])
    ws.append(["Rooms Sold", report.rooms_sold])
    ws.append(["Room-Nights Available", report.total_room_nights])
    ws.append([])

    # Revenue by room type
    ws.append(["Room Type", "Revenue", "Nights Sold", "Average Rate"])
    _style_header_row(ws, ws.max_row, 4)
    for rt in report.revenue_by_room_type:
        ws.append([rt.room_type, float(rt.total_revenue), rt.nights_sold, float(rt.average_rate)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_restaurant_excel(report: RestaurantReport, hotel_name: str) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Restaurant Report"

    ws.append([f"{hotel_name} — Restaurant Sales Report"])
    ws.append([f"Period: {report.period_start} to {report.period_end}"])
    ws.append([])

    ws.append(["Item", "Category", "Qty Sold", "Revenue", "Cost Price", "Margin", "Margin %"])
    _style_header_row(ws, 4, 7)
    for item in report.all_items:
        ws.append([
            item.item_name, item.category, item.quantity_sold,
            float(item.revenue),
            float(item.cost_price) if item.cost_price else "",
            float(item.gross_margin) if item.gross_margin else "",
            f"{item.margin_percent}%" if item.margin_percent else "",
        ])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_inventory_excel(report: InventoryReport, hotel_name: str) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Inventory Report"

    ws.append([f"{hotel_name} — Inventory Movement Report"])
    ws.append([f"Period: {report.period_start} to {report.period_end}"])
    ws.append([])

    ws.append(["Item", "Category", "Unit", "Opening", "Purchases", "Usage", "Wastage", "Closing", "Unit Cost", "Value"])
    _style_header_row(ws, 4, 10)
    for item in report.items:
        ws.append([
            item.item_name, item.category, item.unit_type,
            item.opening_stock, item.purchases, item.usage, item.wastage,
            item.closing_stock, float(item.unit_cost), float(item.total_value),
        ])

    ws.append([])
    ws.append(["", "", "", "", "", "", "", "", "Total Opening:", float(report.total_opening_value)])
    ws.append(["", "", "", "", "", "", "", "", "Total Closing:", float(report.total_closing_value)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_tax_remittance_excel(report: TaxRemittanceReport, hotel_name: str) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Tax Remittance"

    ws.append([f"{hotel_name} — Tax Remittance Report"])
    ws.append([f"Period: {report.period_start} to {report.period_end}"])
    ws.append([])

    ws.append(["Tax Type", "Total Collected", "Remitted", "Pending", "Transactions"])
    _style_header_row(ws, 4, 5)
    for summary in [report.federal_vat, report.state_tdl, report.service_charge]:
        ws.append([
            summary.tax_type.upper(),
            float(summary.total_amount),
            float(summary.remitted_amount),
            float(summary.pending_amount),
            summary.transaction_count,
        ])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ── V2 Export Builders ────────────────────────────────────────

_total_font = Font(bold=True, size=11)
_total_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")


def _add_total_row(ws, row_num: int, col_count: int):
    """Style a total row with bold font and light background."""
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.font = _total_font
        cell.fill = _total_fill
        cell.border = _thin_border


# ── Accommodation V2 ─────────────────────────────────────────

def generate_accommodation_daily_summary_excel(
    rows: list, total_revenue, avg_daily_revenue,
    hotel_name: str, start: str, end: str,
) -> bytes:
    """Daily revenue breakdown: Date | Rooms Sold | Occupancy % | Daily Revenue."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Daily Revenue"

    ws.append([f"{hotel_name} — Accommodation Daily Revenue"])
    ws.append([f"Period: {start} to {end}"])
    ws.append([])

    ws.append(["Date", "Rooms Sold", "Occupancy %", "Daily Revenue"])
    _style_header_row(ws, 4, 4)

    total_sold = 0
    total_rev = 0
    for row in rows:
        ws.append([
            str(row.date),
            row.rooms_sold,
            f"{row.occupancy_rate}%",
            float(row.daily_revenue),
        ])
        total_sold += row.rooms_sold
        total_rev += float(row.daily_revenue)

    # TOTAL row
    total_row = ws.max_row + 1
    ws.append(["TOTAL", total_sold, "", total_rev])
    _add_total_row(ws, total_row, 4)

    # Avg daily revenue
    ws.append([])
    ws.append(["Average Daily Revenue", float(avg_daily_revenue)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_accommodation_monthly_summary_excel(
    rows: list, total_revenue, avg_monthly_revenue,
    hotel_name: str, start: str, end: str,
) -> bytes:
    """Monthly revenue summary: Month | Rooms Sold | Occupancy % | Monthly Revenue."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Monthly Revenue"

    ws.append([f"{hotel_name} — Accommodation Monthly Summary"])
    ws.append([f"Period: {start} to {end}"])
    ws.append([])

    ws.append(["Month", "Rooms Sold", "Occupancy %", "Monthly Revenue"])
    _style_header_row(ws, 4, 4)

    total_sold = 0
    total_rev = 0
    for row in rows:
        ws.append([
            row.month,
            row.rooms_sold,
            f"{row.occupancy_rate}%",
            float(row.monthly_revenue),
        ])
        total_sold += row.rooms_sold
        total_rev += float(row.monthly_revenue)

    total_row = ws.max_row + 1
    ws.append(["TOTAL", total_sold, "", total_rev])
    _add_total_row(ws, total_row, 4)

    ws.append([])
    ws.append(["Average Monthly Revenue", float(avg_monthly_revenue)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_accommodation_transactions_excel(
    rows: list, hotel_name: str, report_date: str,
) -> bytes:
    """Transaction detail: Time | Booking ID | Guest | Room | Description | Amount | Status."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Transactions"

    ws.append([f"{hotel_name} — Accommodation Transactions"])
    ws.append([f"Date: {report_date}"])
    ws.append([])

    ws.append(["Time", "Booking ID", "Guest", "Room", "Description", "Amount", "Status"])
    _style_header_row(ws, 4, 7)

    total_amount = 0
    for row in rows:
        ws.append([
            row.time.strftime("%H:%M:%S") if hasattr(row.time, 'strftime') else str(row.time),
            row.booking_id,
            row.guest_name,
            row.room_number,
            row.description,
            float(row.amount),
            row.status,
        ])
        total_amount += float(row.amount)

    total_row = ws.max_row + 1
    ws.append(["", "", "", "", "TOTAL", total_amount, ""])
    _add_total_row(ws, total_row, 7)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ── Restaurant V2 ────────────────────────────────────────────

def generate_restaurant_daily_sales_excel(
    rows: list, total_revenue, avg_daily_revenue,
    hotel_name: str, start: str, end: str,
) -> bytes:
    """Daily sales: Date | Orders | Food Revenue | Drinks Revenue | Total Revenue."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Daily Sales"

    ws.append([f"{hotel_name} — Restaurant Daily Sales"])
    ws.append([f"Period: {start} to {end}"])
    ws.append([])

    ws.append(["Date", "Orders", "Food Revenue", "Drinks Revenue", "Total Revenue"])
    _style_header_row(ws, 4, 5)

    t_orders = 0
    t_food = 0
    t_drinks = 0
    t_total = 0
    for row in rows:
        ws.append([
            str(row.date),
            row.orders,
            float(row.food_revenue),
            float(row.drinks_revenue),
            float(row.total_revenue),
        ])
        t_orders += row.orders
        t_food += float(row.food_revenue)
        t_drinks += float(row.drinks_revenue)
        t_total += float(row.total_revenue)

    total_row = ws.max_row + 1
    ws.append(["TOTAL", t_orders, t_food, t_drinks, t_total])
    _add_total_row(ws, total_row, 5)

    ws.append([])
    ws.append(["Average Daily Revenue", float(avg_daily_revenue)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_restaurant_monthly_sales_excel(
    rows: list, total_revenue, avg_monthly_revenue,
    hotel_name: str, start: str, end: str,
) -> bytes:
    """Monthly sales: Month | Orders | Food Revenue | Drinks Revenue | Total Revenue."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Monthly Sales"

    ws.append([f"{hotel_name} — Restaurant Monthly Sales"])
    ws.append([f"Period: {start} to {end}"])
    ws.append([])

    ws.append(["Month", "Orders", "Food Revenue", "Drinks Revenue", "Total Revenue"])
    _style_header_row(ws, 4, 5)

    t_orders = 0
    t_food = 0
    t_drinks = 0
    t_total = 0
    for row in rows:
        ws.append([
            row.month,
            row.orders,
            float(row.food_revenue),
            float(row.drinks_revenue),
            float(row.total_revenue),
        ])
        t_orders += row.orders
        t_food += float(row.food_revenue)
        t_drinks += float(row.drinks_revenue)
        t_total += float(row.total_revenue)

    total_row = ws.max_row + 1
    ws.append(["TOTAL", t_orders, t_food, t_drinks, t_total])
    _add_total_row(ws, total_row, 5)

    ws.append([])
    ws.append(["Average Monthly Revenue", float(avg_monthly_revenue)])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_restaurant_transactions_excel(
    rows: list, hotel_name: str, report_date: str,
) -> bytes:
    """Transaction detail: Time | Order # | Guest/Room | Item | Category | Qty | Unit Price | Line Total | Status."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Transactions"

    ws.append([f"{hotel_name} — Restaurant Transactions"])
    ws.append([f"Date: {report_date}"])
    ws.append([])

    ws.append(["Time", "Order #", "Guest/Room", "Item", "Category", "Qty", "Unit Price", "Line Total", "Status"])
    _style_header_row(ws, 4, 9)

    total_amount = 0
    for row in rows:
        ws.append([
            row.time.strftime("%H:%M:%S") if hasattr(row.time, 'strftime') else str(row.time),
            row.order_number,
            row.guest_room,
            row.item_name,
            row.category,
            row.quantity,
            float(row.unit_price),
            float(row.line_total),
            row.status,
        ])
        total_amount += float(row.line_total)

    total_row = ws.max_row + 1
    ws.append(["", "", "", "", "", "", "TOTAL", total_amount, ""])
    _add_total_row(ws, total_row, 9)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
